[workspace]

members = [
    "mango-v4-client-wrapper",
    "rpc-client-wrapper",
    "sysvar-restart-slot-tester",
]

[patch.crates-io]
# for gzip encoded responses
jsonrpc-core-client = { git = "https://github.com/ckamm/jsonrpc.git", branch = "ckamm/http-with-gzip" }


