[package]
name = "sysvar-restart-slot-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
mango-v4-client = { path = "../mango-v4-client" }
# from mango-v4 0.16.0
solana-sdk = "~1.14.9"
# required by anchor 0.27.0
solana-program = "~1.14.16"

