on:
  schedule:
    - cron:  '30 5,17 * * *'
  workflow_dispatch:

name: Run Cargo build

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.66.1
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
